name: 'Push generated file'
description: 'Push a generated file to another repository'
inputs:
  token:
    description: 'Github token for this action (you have to create this in your settings).'
    required: true
  source_file_path:
    description: '"Path" to generated file. Example: path/to/file.md'
    required: true
  destination_repo:
    description: 'Repository to push file to. Example: some_user/some_repo'
    required: true
  destination_folder:
    description: 'Folder or folders to create or use in destination repository.'
    required: true
  target_branch:
    description: '[Optional] set target branch name for the destination repository. Default is "main".'
    required: false
  author:
    description: "[Optional] Name of the commit's author. Default is user name of account doing action."
    required: false
  author_email:
    description: '[Optional] Email for the commit. Default is author@no-reply...'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'green'
